# Install script for directory: /home/matt/git/psopt/examples

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/matt/git/psopt/debug/examples/alpine/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/bike/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/bioreactor/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/brac1/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/breakwell/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/bryson_denham/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/bryson_max_range/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/catmix/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/chain/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/climb/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/coulomb/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/cracking/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/crane/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/dae_i3/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/delay1/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/glider/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/geodesic/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/goddard/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/heat/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/hypersensitive/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/interior_point/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/isoperimetric/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/lambert/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/launch/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/low_thrust/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/lts/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/manutec/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/missile/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/moon/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/mpec/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/notorious/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/obstacle/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/param2/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/predator/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/rayleigh/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/reorientation/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/shuttle_reentry/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/singular5/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/stc1/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/steps/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/twoburn/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/twolinkarm/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/twophase_robot/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/twophase_schwartz/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/user/cmake_install.cmake")
  include("/home/matt/git/psopt/debug/examples/zpm/cmake_install.cmake")

endif()

